### ISSUE TITLE
Add documentation for Data Enrichment

### ISSUE THREAD

**Issue by josephwegner** [keenlabs/keen-gem#101]
Data Enrichment is a super useful feature when sending events to Keen IO. You can see more about it here: https://keen.io/docs/streams/data-enrichment-overview/. 

The JavaScript docs in the API Reference is a good example: https://keen.io/docs/api/?javascript#data-enrichment

They would be good to include in the section about sending events to Keen.

**Comment by waheedel** [comment]
Is this supported but just not documented or not supported at all?

**Comment by josephwegner** [comment]
@waheedel They are supported, just not documented. There are code examples here: https://keen.io/docs/api/?ruby#data-enrichment

**Comment by waheedel** [comment]
Thanks @josephwegner.

**Comment by mptap** [comment]
@josephwegner @tbarn Does this look good? https://github.com/keenlabs/keen-gem/pull/126

**Comment by tbarn** [comment]
Hey @mptap! I'll get this reviewed in the next day or two. Thanks for the PR!
