### ISSUE TITLE
Use newer version of "addressable"?

### ISSUE THREAD

**Issue by meatballhat** [keenlabs/keen-gem#111]
Hello!  I'm one of the humans who maintains [gh](https://github.com/travis-ci/gh).  In some of the apps we maintain that depend on the latest version of `gh`, we are now experiencing a bundler conflict due to `keen` requiring `addressable ~> 2.3.5`.  Can this dependency constraint be updated to allow for more recent versions of `addressable`?

**Comment by meatballhat** [comment]
Ack!  I just saw https://github.com/keenlabs/keen-gem/pull/95

**Comment by waruboy** [comment]
+1, the latest google-api-client gem requires addressable >= 2.5.1

**Comment by hex337** [comment]
I just pushed version 1.0.0 of the gem that should work for this.
