### ISSUE TITLE
Uncaught RuntimeError: eventmachine not initialized: evma_set_pending_connect_timeout

### ISSUE THREAD

**Issue by loren** [keenlabs/keen-gem#22]
Every so often, we get this RuntimeError when calling publish_async due to some as-yet unknown issue we're having with EventMachine+Passenger:

/gems/eventmachine-1.0.3/lib/em/connection.rb:619 in "set_pending_connect_timeout"
/gems/eventmachine-1.0.3/lib/em/connection.rb:619 in "pending_connect_timeout="
/gems/em-http-request-1.0.3/lib/em-http/http_connection.rb:61 in "block in activate_connection"
/gems/eventmachine-1.0.3/lib/eventmachine.rb:672 in "bind_connect"
/gems/em-http-request-1.0.3/lib/em-http/http_connection.rb:54 in "activate_connection"
/gems/em-http-request-1.0.3/lib/em-http/http_connection.rb:89 in "setup_request"
/gems/em-http-request-1.0.3/lib/em-http/http_connection.rb:8 in "post"
/gems/keen-0.7.7/lib/keen/http.rb:75 in "post"
/gems/keen-0.7.7/lib/keen/client/publishing_methods.rb:69 in "publish_async"

Sometimes the EM problem causes an error that the Keen gem catches and bubbles up as a Keen::Error:

Keen::Error: Keen IO Exception: An EventMachine loop must be running to use publish_async calls
/gems/keen-0.7.7/lib/keen/http.rb:53 in "initialize"
/gems/keen-0.7.7/lib/keen/client/publishing_methods.rb:66 in "new"
/gems/keen-0.7.7/lib/keen/client/publishing_methods.rb:66 in "publish_async"

I'd rather just catch the Keen::Error in my application code and not have to look out for the RuntimeError, too.

**Comment by songyiyang** [comment]
This works, thanks!
