### ISSUE TITLE
Environment initialization for noop support in dev/testing

### ISSUE THREAD

**Issue by ralph-tice** [keenlabs/keen-gem#37]
Currently the gem is missing a method to disable publishing of events for non-production usages which means we have to wrap all our calls in environment checks.  It would be great if the gem had an initializer to make all Keen calls a no-op.

**Comment by antonshevchenko** [comment]
@dzello What would you suggest to do in order to not make Keen API calls in our rspec tests?

**Comment by antonshevchenko** [comment]
Adding this to my spec file worked!

```ruby
before {
  allow(Keen).to receive(:publish_async).and_return nil
}
```

**Comment by josephwegner** [comment]
Looks like stubbing is a fine solution. Closing.
