### ISSUE TITLE
Is there a way to increase the HTTP timeout?

### ISSUE THREAD

**Issue by wetzler** [keenlabs/keen-gem#57]
Is there any easy way to increase the time to wait for an HTTP response?
My (large) requests work OK in the Keen IO workbench but timeout after ~3 minutes when using keen gem.

```
rb:249:in `rescue in get_response': Keen IO Exception: Couldn't perform  on Keen IO: Net::ReadTimeout (Keen::HttpError)
``
```

**Comment by wetzler** [comment]
I noticed that PR was merged and the docs now have this option, yay! 
keen = Keen::Client.new(:read_timeout => 300)

However, whenever I run a query, it is consistently timing out after 2 minutes, not 5 minutes. Is there another timeout limit that needs to be raised somehow?

**Comment by chaudhary27** [comment]
Getting the same issue. exact error is 
`Keen::HttpError: Keen IO Exception: Couldn't perform  on Keen IO: Net::ReadTimeout`

**Comment by josephwegner** [comment]
Haven't heard from this in a while. Gonna close and let it resurface if it still exists.

**Comment by JonKernPA** [comment]
I'm with @wetzler in that the timeout still occurs at 120 seconds even if I set the read_timeout at 300 when I am trying to do an extraction (on an admittedly large, 10MB dataset).

**Comment by josephwegner** [comment]
@JonKernPA Are you using the HTTP Read Timeout option?

Check this out: https://github.com/keenlabs/keen-gem#http-read-timeout

**Comment by JonKernPA** [comment]
I think so... and I bumped the gem to 0.9.7

We have it wrapped inside one of our gems, so maybe I need to be more thorough and make sure there is not some oddity :-p

```
      def make_keen(options = {})
        project_id = options.include?(:project_id) ? options[:project_id] : keen_config(:project_id)
        return nil if project_id.blank?
        klass = testing? ? Keen::Client::Stubbed : Keen::Client
        klass.new(
          project_id: project_id,
          write_key: options.include?(:write_key) ? options[:write_key] : keen_config(:write_key),
          read_key: options.include?(:read_key) ? options[:read_key] : keen_config(:read_key),
          read_timeout: 300
        )
      end
```
