### ISSUE TITLE
Environment vars not ideal for some environments

### ISSUE THREAD

**Issue by wetzler** [keenlabs/keen-gem#58]
[This was shared by another developer; I'm sharing it here on their behalf]

I'm starting to use the keen.io ruby gem and I have feedback. On some hosting systems (like EngineYard), it is very complicated to configure libraries using environment variables. Instead, they recommend using a yaml file which is in a backed-up folder https://support.cloud.engineyard.com/entries/36999448-Environment-Variables-and-Why-You-Shouldn-t-Use-Them. I looked at the code (default_client specifically) and it looks like a "manual configuration" from an initializer would be a bit fragile. I would have to make sure I artificially set the env vars before bundler is loaded, so that the default client is not generated with empty credentials. That, or create my own instance of Keen::Client (which I'm probably going to do). Well - just a bit of feedback; in some case, using env vars is really not possible (which actually made me delay the use of keen.io several times already).

**Comment by thbar** [comment]
@dzello thanks for the feedback - I'm revisiting this and this is going to be helpful.
