### ISSUE TITLE
Listing collections, KEEN_MASTER_KEY requirement.

### ISSUE THREAD

**Issue by fwl** [keenlabs/keen-gem#60]
Hi there!

Isn't too strict and probably less secure that the KEEN_MASTER_KEY is required to run `Keen.event_collections`?

From the documentation the general rule seems to be that for reading and querying the KEEN_READ_KEY is what's needed. While the KEEN_MASTER_KEY is required for destructive operations such as deleting.

The result of the current requirement means that in practical terms for exploratory querying among teams and/or team members one really needs to hand around the KEEN_MASTER_KEY more deliberately than one otherwise would for reading and querying data.

Isn't this requirement for `Keen.event_collections` something that should be re-considered?

Thank you.

**Comment by dzello** [comment]
Thanks for opening the issue and starting the conversation!

The security stuff is handled at the API layer, so not much we can do in context of the SDK. That said, I do think you raise some interesting questions about how to handle security when exploratory querying is needed.

A good place to discuss this further would be Keen's [developer group](https://groups.google.com/forum/#!forum/keen-io-devs). Would you mind posting your question over there?

**Comment by fwl** [comment]
Hi @dzello and thank you for your response. I wouldn't mind continuing the conversation but I don't have a Google account to post there.

**Comment by dzello** [comment]
No worries, I'll go ahead and cross-post it for you :)

**Comment by dzello** [comment]
Posted – https://groups.google.com/forum/#!topic/keen-io-devs/KkOybgGXn2o

**Comment by dzello** [comment]
2 replies so far - https://groups.google.com/forum/#!topic/keen-io-devs/KkOybgGXn2o

**Comment by dzello** [comment]
Quoting one of them:

> Presently, there is a way you can work around this. Write a server-side endpoint capable of proxying requests for schema. Authenticate the endpoint by making the client prove it has the read key (or whatever other authentication you're employing). In this setup the master key never has to leave the server.
