### ISSUE TITLE
require 'keen' takes almost a minute at run-time?

### ISSUE THREAD

**Issue by angelacode** [keenlabs/keen-gem#62]
I used `benchmark` to measure the time of keen compared to other gems when running on iron.io:

cgi:   0.000000   0.000000   0.000000 (  0.005616)
iron_cache:   0.070000   0.030000   0.100000 (  0.107393)
keen:   0.080000   0.020000  54.830000 ( 69.544284)
rollbar:   0.010000   0.000000   0.010000 (  0.009601)
active_spport:   0.020000   0.000000   0.020000 (  0.01519)

This report shows the user CPU time, system CPU time, the sum of the user and system CPU times, and the elapsed real time. The unit of time is seconds.

**Comment by dzello** [comment]
Interesting, thanks for opening this issue. Does that lag happen each time or was an outlier?

**Comment by angelacode** [comment]
Hi it seems to be every time I run it. I run it in an iron worker tht spins up for every request. 



On Thu, Jan 22, 2015 at 4:52 PM -0800, "Josh Dzielak" <notifications@github.com> wrote:










Interesting, thanks for opening this issue. Does that lag happen each time or was an outlier?





On Wed, Jan 21, 2015 at 10:21 PM, angelacode <notifications@github.com>


wrote:

**Comment by angelacode** [comment]
Still seem to be happpening:

    cgi:   0.010000   0.000000   0.010000 (  0.007710)
    iron_cache:   0.110000   0.010000   0.120000 (  0.135899)
    keen:   0.100000   0.030000  49.860000 ( 58.807518)

**Comment by dzello** [comment]
K, thanks for reporting back. Question... what code is the `benchmark` statement around?

Also, paging @stephenitis, any ideas? :)

**Comment by angelacode** [comment]
The require statement. Require 'keen'
Came in again at 400 seconds.  When keen is required again for a different method it is 0 seconds effectively. So once loaded it is fine. 

Timfong88@gmail.com
Sent from phone




On Sun, Jan 25, 2015 at 7:53 PM -0800, "Josh Dzielak" <notifications@github.com> wrote:












K, thanks for reporting back. Question... what code is the benchmark statement around?



Also, paging @stephenitis, any ideas? :)

**Comment by dzello** [comment]
Definitely a mystery on our hands. My tests locally show requiring it is pretty fast. I wonder if it could be something with Iron's gem server or connection to Rubygems? Would you be willing to open up a ticket with them and see what they have to say?

**Comment by angelacode** [comment]
Yeah locally it works fine too. Got off a call with them today. Thry don't know either. Hm thanks. 



On Tue, Jan 27, 2015 at 3:07 PM -0800, "Josh Dzielak" <notifications@github.com> wrote:












Definitely a mystery on our hands. My tests locally show requiring it is pretty fast. I wonder if it could be something with Iron's gem server or connection to Rubygems? Would you be willing to open up a ticket with them and see what they have to say?

**Comment by dzello** [comment]
Hmm. Is it just gem ‘keen’ in the gemfile?

**Comment by josephwegner** [comment]
@angelacode are you still having this issue? I haven't heard of it elsewhere. I'm going to close for now, but feel free to respond back if it's still happening.
