### ISSUE TITLE
Add support for caching

### ISSUE THREAD

**Issue by wetzler** [keenlabs/keen-gem#73]
When providing a max_age parameter to a query using the Ruby gem, it fails with:

`in`escape': undefined method `encoding' for 300:Fixnum (NoMethodError)`

It should be possible to add a caching parameter (max_age) to a query like this:

puts Keen.count("Content Engagement", 
    :filters => [{
        "property_name" => "siteId",
        "operator" => "eq",
        "property_value" => 2563
    }],
    :max_age => 300
  )

I am kind of surprised that the library doesn't work with any provided property (I thought it did). Maybe it doesn't work with this one specifically because the value is numeric?

Reference:
https://keen.io/docs/data-analysis/caching/

**Comment by josephwegner** [comment]
Gonna close this one, since `max_age` is deprecated. I will create new issues for our new caching features.
