### ISSUE TITLE
Doubt about relative timeframes

### ISSUE THREAD

**Issue by facundofarias** [keenlabs/keen-gem#79]
Is there a way, to  know the attributes start and end of a timeframe, given its "code"?
Like for example, if I use `this_month`, I would like to know its attributes, in this case:
```
"timeframe" => {
  :"start" => "2015-07-01T00:00:00.000Z",
  :"end" => "2015-07-31T00:00:00.000Z"
}
```
Or the other way around.
Thanks!

**Comment by hex337** [comment]
Hey there @facundofarias. There is no way to pull the `start` and `end` bits from our "codified" timeframes. 

The way timeframes work though is >= to the start and < the end. So if you're looking to build absolute time frames the same way we do, you can just modify the dates using the Ruby date library.

To get one month, you just get from the 1st of that month at 00:00:00 to the first of the next month at 00:00:00.

In your example, it would equate to this:

```
"timeframe" => {
  :"start" => "2015-07-01T00:00:00.000Z",
  :"end" => "2015-08-01T00:00:00.000Z"
}
```

**Comment by facundofarias** [comment]
Hey @hex337, thanks for your response.

Yes, I know I can do that. The thing is, I have to integrate some KeenIO queries with other external systems, and I was willing to use as input only the timeframes as Keen does. The thing is, the periods might vary depending on the client, or the kind of analysis we are doing, because of that we thought that maybe, the SDK would provide some kind of mechanism to expose these functionality. No issues, we will try to solve it on a different way. Thanks anyway!
