### ISSUE TITLE
Logging queries

### ISSUE THREAD

**Issue by agseco** [keenlabs/keen-gem#83]
Hi,

Does the keen-gem support logging every query being sent out?

In the Java Keen Client it's pretty straight forward and documented: https://github.com/keenlabs/KeenClient-Java#logging

I have explored the official docs, issues in this repo as well as googled for it and couldn't find anything in this regard.

Perhaps it's supported but it's rather a lack of documentation?

Regards.

**Comment by hex337** [comment]
So, there is logging right now, but only for errors. If you could open up an issue asking for the feature, that would help us track it!

**Comment by agseco** [comment]
Thanks for your reply @hex337 

I have created the issue #84 following your indications; I hope this is what you expected me to do :smile: 

Cheers.

**Comment by josephwegner** [comment]
Closing this one, and can continue discussion in #84
