### ISSUE TITLE
Support for queries logging

### ISSUE THREAD

**Issue by agseco** [keenlabs/keen-gem#84]
For debugging purposes, it would be great to have a mechanism such that allows logging every query issued to Keen.io.

As an example, the Java client already supports it: https://github.com/keenlabs/KeenClient-Java#logging

**Comment by agseco** [comment]
Anybody please label it properly.

Thanks.

**Comment by myrridin** [comment]
A PR was merged to address this request. I believe this issue should be satisfied by the newest version, 1.1.1
