### ISSUE TITLE
Generated Scoped Key fails with Invalid API Key error

### ISSUE THREAD

**Issue by subbuthepeaceful** [keenlabs/keen-gem#86]
Using the gem to generate a scoped key and subsequently using that key in a query throws an Invalid API Key Error.

The newly generated scoped key can be successfully encrypted/decrypted, but cannot be used.

To verify, please initialize a new Keen Client with a generated scoped key corresponding to a filter, say

data = { "filters" => [{ "property_name" => "<SOME PROPERTY>", "operator" => "eq", "property_value" => "<SOME VALUE>" }] } 
scoped_key_generator = Keen::ScopedKey.new master_key, data 
scoped_read_key = scoped_key_generator.encrypt! 

client = Keen::Client.new( project_id: <PROJECT_ID>, read_key: scoped_read_key ) 

Now, perform a count query on some collection in the project
client.count(...)

**Comment by tbarn** [comment]
Fixed with #88
