### ISSUE TITLE
`uninitialized constant Keen::ScopedKey`

### ISSUE THREAD

**Issue by jfeldstein** [keenlabs/keen-gem#90]
I'm using the keen gem to give scoped keys to clients for rendering charts in JS. 

In my rails model, I'm using: 

```
  before_save :set_scoped_keen_key!, if: Proc.new{scoped_keen_key.blank?}

  def set_scoped_keen_key!
    # Locks all queries the partner can see to those involving their own content.
    self.scoped_keen_key = Keen::ScopedKey.new(ENV['KEEN_MASTER_KEY'], {
      "allowed_operations" => [ "read" ],
      "filters" => [{
        "property_name" => "Content.source.name",
        "operator" => "exists",
        "property_value" => true
        },{
        "property_name" => "Content.source.name",
        "operator" => "eq",
        "property_value" => self.partner_brand.content_source_name
    }]}).encrypt!
  end
```

But am getting the error: 

```
uninitialized constant Keen::ScopedKey

Extracted source (around line #8):
  
  def set_scoped_keen_key!
    # Locks all queries the partner can see to those involving their own content.
    self.scoped_keen_key = Keen::ScopedKey.new(ENV['KEEN_MASTER_KEY'], {  # <== Error here
      "allowed_operations" => [ "read" ],
      "filters" => [{
        "property_name" => "Content.source.name",
```

I've set in `.env`:

```
KEEN_PROJECT_ID=...
KEEN_READ_KEY=...
KEEN_MASTER_KEY=...
```

**Comment by josephwegner** [comment]
Hey Jordan,

How are you loading Keen in in this particular file? Are you requiring it at the top?

**Comment by jfeldstein** [comment]
I need to explicitly require it? 

Usually gems included via Gemfile are included by default.

**Comment by jfeldstein** [comment]
I've added `require 'keen'` to the top. No effect.

**Comment by josephwegner** [comment]
This is odd - I just copied your exact code and tested it locally, and it's working for me.

Do you know what version of the gem you are using?

**Comment by jfeldstein** [comment]
0.7.8

**Comment by josephwegner** [comment]
Oh, that could totally be the issue. We're currently on `0.9.5`, which should be 2 breaking versions since what you're using! Almost certainly the docs are different, but I would also guess that the scoped key implementation `0.7.8` wouldn't work in any form anymore - that was one of the breaking changes I believe.

Can you upgrade to the latest version on rubygems?

**Comment by jfeldstein** [comment]
That did it. Thanks!




~ Jordan

See what I'm into on AngelList <https://angel.co/jordan-feldstein>
