### ISSUE TITLE
README contains broken link to keen-gem-example

### ISSUE THREAD

**Issue by monfresh** [keenlabs/keen-gem#94]
Hi. I just started exploring this repo and noticed the link to the `keen-gem-example` app points to a nonexistent app on Heroku. I was actually expecting the link to point to a repo, not a Heroku app. I looked through all your repos and didn't see one that looks like a Ruby example app, but perhaps I didn't look hard enough. Is there one?

**Comment by tbarn** [comment]
Hey @monfresh! Sorry I missed this! 

It looks like that application had been shut down. I'll look into if we can turn it back on. Otherwise, we'll remove the link.

**Comment by tbarn** [comment]
Following up, we don't have access to that application anymore. Sorry about that, we'll get it removed. Is there something in particular you'd like to check out in a sample application? We might have something else.
